### ISSUE TITLE
VTK pin

### ISSUE THREAD

**Issue by dfroger** [conda-forge/mayavi-feedstock#1]
VTK need not to be pinned exactly `7.1.0`, `>= 7.1` shoud be enough

**Comment by jakirkham** [comment]
Does there need to be an upper bound or is the lower bound all that is needed?

**Comment by dfroger** [comment]
As lower bound, we need VTK 7.1.0, with at least build number 2 (can this be specified?). The reason is that we need this fix (https://github.com/conda-forge/vtk-feedstock/pull/15, https://github.com/conda-forge/vtk-feedstock/pull/19).

7.1.0 is currently the [lastest VTK release](http://www.vtk.org/download/), but we could set an upper bound to <7.2 or <8  for the future.

**Comment by Korijn** [comment]
I would recommend setting `=7.1.*` in that case
