### ISSUE TITLE
is there a reason for vtk pinned to 7.1

### ISSUE THREAD

**Issue by satra** [conda-forge/mayavi-feedstock#11]
this recipe pins vtk to 7.1. is there a specific reason for this?

- we have just discovered an i/o bug that seems to write incorrect vtk files with 7.1 - this bug does not appear exist in 7.0.

**Comment by dfroger** [comment]
Hi, I think we can try to make Mayavi work with VTK 7.0. We will need to apply a [path](https://github.com/conda-forge/vtk-feedstock/pull/15) fixing a segault during Mayavi installation.

**Comment by dfroger** [comment]
If Mayavi is built we VTK 7.1, can we just install it with VTK 7.0? I think we need another Mayavi package built with VTK 7.0?

**Comment by dfroger** [comment]
By the way, what is the IO bug? Another solution would be to help VTK dev fix it, and backport the patch to the VTK feedstock, waiting VTK 7.1.2 which will include the patch.

**Comment by satra** [comment]
turns out it's not quite a bug, but a difference between in implementation between 7.0 and 7.1 (scalarArray).GetSize() differs from (scalarArray).GetDataSize() between those two versions. i do have things working with 7.1 for now, so things are ok for the moment. i will post to vtk to ask about the difference.

**Comment by jakirkham** [comment]
What about moving to 8.1?

**Comment by larsoner** [comment]
We're on 9.1 nowadays so I'll close
