### ISSUE TITLE
Mayavi as built requires pyqt=4 and the default in conda-forge (with mpl=2.0.2) is 5

### ISSUE THREAD

**Issue by Cadair** [conda-forge/mayavi-feedstock#14]
is the best solution to put `pyqt=4` in the requirements for mayavi?

**Comment by grlee77** [comment]
I had pinned to `<5` in #13, but there was a seemingly unrelated failure on CircleCI, so I did not merge it yet.  There is a similar issue with `pyface` and `traitsui` that we are working to resolve now in conda-forge/pyface-feedstock#10

**Comment by smithsp** [comment]
I am seeing this.  Mention @logan-nc.

**Comment by grlee77** [comment]
@smithp  : what is the problem you are seeing exactly? The recipe was modified to require pyqt =4.* so it should no longer attempt to install when qt5 is present.  If it is doing so, perhaps there are some older broken builds that we need to remove.

That said, there was recently a 6.0 release of the `traitsui` dependency of mayavi that supports both Qt4 and Qt5.  I can try making a PR to pin `traitsui >6` and remove the pinning on pyqt.

**Comment by grlee77** [comment]
Actually, I think a new mayavi release will be required before we can support Qt5 (and VTK 8.1).  Hopefully now that the traitsui and pyface dependencies have been updated, mayavi will as well. 

As is, Qt5 and VTK 8.1 do work when I tested locally if the recipe is modified to use the master branch of mayavi.

**Comment by smithsp** [comment]
@grlee77 Thanks for digging deeper.  I installed mayavi from conda-forge.  It seemed content to have qt5 installed, but then I was getting a problem getting a backend for traits (quoting from @logan-nc in https://github.com/gafusion/OMFIT-source/issues/2667):
```
>>> import mayavi.mlab as mmlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/atom/conda/lib/python2.7/site-packages/mayavi/mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/p/atom/conda/lib/python2.7/site-packages/mayavi/tools/camera.py", line 25, in <module>
    from .engine_manager import get_engine
  File "/p/atom/conda/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 12, in <module>
    from mayavi.preferences.api import preference_manager
  File "/p/atom/conda/lib/python2.7/site-packages/mayavi/preferences/api.py", line 4, in <module>
    from .preference_manager import preference_manager
  File "/p/atom/conda/lib/python2.7/site-packages/mayavi/preferences/preference_manager.py", line 29, in <module>
    from traitsui.api import View, Group, Item
  File "/p/atom/conda/lib/python2.7/site-packages/traitsui/api.py", line 41, in <module>
    from .editors.api import (BooleanEditor, ButtonEditor,
  File "/p/atom/conda/lib/python2.7/site-packages/traitsui/editors/__init__.py", line 27, in <module>
    from .api import (toolkit, BooleanEditor, ButtonEditor,
  File "/p/atom/conda/lib/python2.7/site-packages/traitsui/editors/api.py", line 24, in <module>
    from .code_editor import CodeEditor
  File "/p/atom/conda/lib/python2.7/site-packages/traitsui/editors/code_editor.py", line 36, in <module>
    class ToolkitEditorFactory ( EditorFactory ):
  File "/p/atom/conda/lib/python2.7/site-packages/traitsui/editors/code_editor.py", line 48, in ToolkitEditorFactory
    mark_color = Color( 0xECE9D8 )
  File "/p/atom/conda/lib/python2.7/site-packages/traits/traits.py", line 522, in __call__
    return self.maker_function( *args, **metadata )
  File "/p/atom/conda/lib/python2.7/site-packages/traits/traits.py", line 1236, in Color
    return ColorTrait( *args, **metadata )
  File "/p/atom/conda/lib/python2.7/site-packages/traitsui/toolkit_traits.py", line 7, in ColorTrait
    return toolkit().color_trait( *args, **traits )
  File "/p/atom/conda/lib/python2.7/site-packages/traitsui/toolkit.py", line 152, in toolkit
    _toolkit = _import_toolkit(ETSConfig.toolkit)
  File "/p/atom/conda/lib/python2.7/site-packages/traitsui/toolkit.py", line 83, in _import_toolkit
    return __import__( name, globals=globals(), level=1 ).toolkit
  File "/p/atom/conda/lib/python2.7/site-packages/traitsui/qt4/__init__.py", line 24, in <module>
    import toolkit
  File "/p/atom/conda/lib/python2.7/site-packages/traitsui/qt4/toolkit.py", line 24, in <module>
    from pyface.qt import QtCore, QtGui, qt_api
  File "/p/atom/conda/lib/python2.7/site-packages/pyface/qt/QtCore.py", line 4, in <module>
    from PyQt4.QtCore import *
ImportError: No module named PyQt4.QtCore
```
If you haven't used mayavi and matplotlib in the last 5 years, then you
probably haven't set your backend globals like I have had to in the past and it imports fine.
Like you, if I comment out bash_profile env variables
```
#export QT_API=pyqt # to avoid mayavi.mlab errors
#export ETS_TOOLKIT=qt4 # to avoid mayavi.mlab errors
```
It imports. But trying to open a figure throws an error.
Here is trying to run the FOCUS plot script.
```
Exception in script of module OMFIT['GPEC']:
Error in "plot_control_modes_3d.py" at line  85
    fig = mayavi.mlab.figure(bgcolor=(1, 1, 1), fgcolor=(0, 0, 0), size=(600, 500))
ImportError: Could not import backend for traits
_______________________________________________________________________________
Make sure that you have either the TraitsBackendWx or the TraitsBackendQt
projects installed. If you installed Mayavi with easy_install, try
easy_install <pkg_name>. easy_install Mayavi[app] will also work.

If you performed a source checkout, be sure to run 'python setup.py install'
in Traits, TraitsGUI, and the Traits backend of your choice.

Also make sure that either wxPython or PyQT is installed.
wxPython: http://www.wxpython.org/
PyQT: http://www.riverbankcomputing.co.uk/software/pyqt/intro
```
(end quoting)

So I was able to avoid the problems of the backend by installing the qt4 package and setting `ETS_TOOLKIT` to `qt4`, but then I had problems with the graphics driver or OPENGL not being current enough, so I gave up after trying to install various versions of `vtk`.  It is possible I had an older version of mayavi installed.  Here is the current status:
```
$ conda list \(qt\|mayavi\)
# packages in environment at /p/atom/conda:
#
# Name                    Version                   Build  Channel
mayavi                    4.5.0               np112py27_1    conda-forge
pyqt                      5.6.0                    py27_5    conda-forge
qt                        5.6.2                         6    conda-forge
```

I will look forward to a newer release of mayavi then (and hopefully we can get upgraded hardware to run it).

**Comment by grlee77** [comment]
@smithsp 
I don't think it is going to work as long as you have pyqt 5 because I don't think it is supported in mayavi 4.5.0.  I think you will have to use `conda install -c conda-forge "pyqt<5" mayavi` to make sure you get the most recent mayavi build and pyqt4. This should result in a mayavi package with build number 3 (the build string will end in `_3`). 

We probably need to remove some of the older `mayavi` builds  to avoid the problem you are seeing where installing mayavi along pyqt5 is allowed. The `pyqt 4.*` pinning was introduced in build 2 so the existing build 2 and 3 should be okay, but older ones may need to be removed.  cc @jakirkham: you helped out on this previously for pyface.  Do we need to remove some builds here as well?

**Comment by larsoner** [comment]
Mayavi no longer requires PyQt4 so I'll close
