### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by mivade** [conda-forge/mayavi-feedstock#15]
Is there anything holding back packaging for Python 3.6?

**Comment by grlee77** [comment]
There is a PR for this at #13 that has an unresolved CircleCI error.  Any help determining what the cause of that is would be appreciated.

The package also does not work properly with PyQt 5 (which is now the default with Matplotib 2 packages), so it needed to be pinned to PyQt 4.  It is possible that the current master of mayavi works with PyQt 5 (I haven't checked), but I don't think the released version packaged here does.

**Comment by mivade** [comment]
My mistake, I thought I had checked the pull requests before submitting this bug, but evidently not. I'll close this and move the conversation over there.
