### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by dfroger** [conda-forge/mayavi-feedstock#3]
We first need OSX support for VTK: https://github.com/conda-forge/vtk-feedstock/issues/10

**Comment by christianbrodbeck** [comment]
The conda-forge [docs](https://conda-forge.org/docs/recipe.html#avoid-dependencies-outside-of-conda-forge) seem to suggest that it is possible to have dependencies from other channels, might this be an option?

**Comment by jakirkham** [comment]
So there is a build of VTK for macOS now, but it is for VTK 8.1.0. Would it be possible to use that?
