### ISSUE TITLE
How to deal with lack of x server?

### ISSUE THREAD

**Issue by moorepants** [conda-forge/mayavi-feedstock#7]
In this recipe for linux:

https://github.com/conda-forge/staged-recipes/pull/2306

I'm getting this error:

```
===== testing package: yeadon-1.3.0-py27_0 =====
import: 'yeadon'
run_test.py: cannot connect to X server 
TESTS FAILED: yeadon-1.3.0-py27_0
```
`yeadon` import `mayavi`. How to import mayavi on CircleCI in the tests section of the conda recipe? I see that you all mock the x server in the build.sh script but I'm not sure how to get that working for the tests that are run.

**Comment by dfroger** [comment]
Hi @moorepants, yes mayavi recipe uses [xvfb](https://en.wikipedia.org/wiki/Xvfb) in [build.sh](https://github.com/conda-forge/mayavi-feedstock/blob/1d2e2f70218283a5ac39c8e0c69065ad570c868a/recipe/build.sh#L5). `xvfb` is recommanded in [mayavi documentation](http://docs.enthought.com/mayavi/mayavi/tips.html#rendering-using-the-virtual-framebuffer). [yum_requirements](https://github.com/conda-forge/mayavi-feedstock/blob/1d2e2f70218283a5ac39c8e0c69065ad570c868a/recipe/yum_requirements.txt) installes the `xorg-x11-server-Xvfb` package.

I see that `yeadon` uses `xvfb-run` in [test.sh](https://github.com/conda-forge/mayavi-feedstock/blob/1d2e2f70218283a5ac39c8e0c69065ad570c868a/recipe/build.sh#L5), does this fix the problem?

**Comment by moorepants** [comment]
Yes, thank you. I ended up figuring out how to do it on my own. I had to extract the conda test imports section into a separate python file then create that test.sh file with xvfb-run.
